language: objective-c
osx_image: xcode11.3
env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8
    - WORKSPACE="IBAnimatable.xcworkspace"
    - IOS_FRAMEWORK_SCHEME="IBAnimatable"
    - IOS_APP_SCHEME="IBAnimatableApp"
  matrix:
    - DESTINATION="OS=13.3,name=iPad Pro (12.9-inch) (3rd generation)" SCHEME=${IOS_FRAMEWORK_SCHEME}    APP_SCHEME=${IOS_APP_SCHEME}
    - DESTINATION="OS=12.2,name=iPhone 6s Plus"        SCHEME=${IOS_FRAMEWORK_SCHEME}    APP_SCHEME=${IOS_APP_SCHEME}
    - DESTINATION="OS=13.3,name=iPhone 11 Pro Max"        SCHEME=${IOS_FRAMEWORK_SCHEME}    APP_SCHEME=${IOS_APP_SCHEME}
before_install:
  - bundle install
  - brew update
  - brew remove swiftlint || brew install swiftlint
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Framework in Release
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release | xcpretty;

  # Test Framework in Release
  - xcodebuild clean -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;

  # Build App in Release
  - xcodebuild clean build -workspace "$WORKSPACE" -scheme "$APP_SCHEME" -destination "$DESTINATION" -configuration Release | xcpretty;

  - bundle exec danger

after_success:
   - sleep 10 # Workaround for https://github.com/travis-ci/travis-ci/issues/4725
   - bash <(curl -s https://codecov.io/bash) -J 'IBAnimatable'
